# AULA 4 - Prática 2: Redes Convolucionais


Aula 4- Aula Assíncrona
https://www.youtube.com/watch?v=yvsJDLn6Ots&ab_channel=MoacirAntonelliPonti

---

## PyTorch Custom Dataset

- Customização de dataset

---

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

Para definir um dataset personalizado, para qualquer tipo de dados, projetamos uma classe herdando de `Dataset` e contendo os métodos:
- `__init__` que vai atribuir os dados
- `__len__` que retorna o tamanho do dataset
- `__getitem__` que retorna um item baseado em um índice

In [2]:
class MyDataset(Dataset):
    def __init__(self, data):
        self.data = data
        
    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, idx):
        return self.data[idx]

* Essa classe será usada para armazenar os dados 

In [5]:
random_data = np.random.randint(0, 20, (20)) # valores aleatórios 
print('Dados:', random_data)

dataset = MyDataset(random_data) # valores acima na classe
print('Total de exemplos no dataset:', len(dataset))
print('Podemos usar colchetes pois implementamos o __getitem__, exemplo:', dataset[2])
print(dataset[0:5])

Dados: [ 5  0 12  8  3 10  2  5 17 13 19 16 18 16 15 10  8 14 17 10]
Total de exemplos no dataset: 20
Podemos usar colchetes pois implementamos o __getitem__, exemplo: 12
[ 5  0 12  8  3]


In [7]:
# usando dataloader da aula passada
train_dataloader = DataLoader(dataset, batch_size=6, shuffle=False) # como shuffle ta False, ele pega os 1ºs 6 itens
next_batch = next(iter(train_dataloader))
print(next_batch)

tensor([ 5,  0, 12,  8,  3, 10])


In [8]:
iterator_train = iter(train_dataloader)
next_batch = next(iterator_train)
print(next_batch) # 6 primeiros elementos
next_batch = next(iterator_train)
print(next_batch) # segunda leva de 6 elementos
next_batch = next(iterator_train)
print(next_batch) # terceira leva de 6 elementos
next_batch = next(iterator_train)
print(next_batch) # ultima leva com os que sobraram
## next_batch = next(iterator_train)
## print(next_batch) # gera erro pois nao há mais items para retornar

tensor([ 5,  0, 12,  8,  3, 10])
tensor([ 2,  5, 17, 13, 19, 16])
tensor([18, 16, 15, 10,  8, 14])
tensor([17, 10])


In [9]:
# outro dataset contendo 10 instancias com 4 features cada
random_data2 = np.random.randint(1,5, (10, 4))
print('Dados: ', random_data2)

dataset2 = MyDataset(random_data2)
print('Total de exemplos no dataset: ', len(dataset2))
print('Podemos usar colchetes pois implementamos o __getitem__, exemplo:', dataset2[2])
print(dataset2[:3])

Dados:  [[1 4 4 3]
 [3 4 4 2]
 [1 1 4 3]
 [2 4 3 1]
 [2 4 2 3]
 [2 4 3 4]
 [1 3 2 3]
 [2 2 3 1]
 [2 4 3 2]
 [1 4 4 3]]
Total de exemplos no dataset:  10
Podemos usar colchetes pois implementamos o __getitem__, exemplo: [1 1 4 3]
[[1 4 4 3]
 [3 4 4 2]
 [1 1 4 3]]


In [10]:
# dataloader 2
train_dataloader2 = DataLoader(dataset2, batch_size=3, shuffle=True) # shuffle true, valores aleatrios
iterator_train = iter(train_dataloader2)

In [11]:
next_batch = next(iterator_train, None)
while next_batch != None: # iterar pelos batches
    print(next_batch) # vale lembrar que o shuffle ta True, então os valores sao aleatorios no dataset
    next_batch = next(iterator_train, None)

tensor([[1, 3, 2, 3],
        [2, 2, 3, 1],
        [1, 1, 4, 3]])
tensor([[1, 4, 4, 3],
        [1, 4, 4, 3],
        [2, 4, 3, 1]])
tensor([[2, 4, 3, 2],
        [3, 4, 4, 2],
        [2, 4, 2, 3]])
tensor([[2, 4, 3, 4]])


---