# AULA 2 DEMONSTRAÇÃO - Multi-Layer Perceptron

Aula 2 - Aula Assíncrona
https://www.youtube.com/watch?v=PMrKHx_U--w&ab_channel=MoacirAntonelliPonti

---

## Perceptrons e Multi-layer Perceptrons

- Implementando um modelo de perceptron com Pytorch

---

In [9]:
import torch

### Modelo Linear

* Construir um modelo linear com classes orientadas a objeto
    * Modelo linear: w.X + b

In [10]:
class Model():
    # construtor inicializa os parametros
    def __init__(self, num_inputs):
        # w inicial: amostrando de uma distribuicao normal media 0 e desvio padrao 1
        self.w = torch.normal(0, 1, (num_inputs, 1))
        # b inicial: valor constante 1 ou 0, as vezes com 1/total de classes
        self.b = torch.zeros(1)

    # forward: de x até a saida
    def forward(self, X):
        # X w + b
        return X @ self.w + self.b # multipliação e soma matricial

    # funcao custo
    def loss(self, y, y_hat):
        yreshape = y.reshape(y_hat.shape)
        l = (y_hat - yreshape)**2/2
        return l.mean()

In [11]:
model = Model(2)
model.w, model.forward(torch.tensor([[1,1]], dtype = torch.float32))

(tensor([[-0.2601],
         [ 1.5535]]),
 tensor([[1.2934]]))

### Modelo em Prática

- Testar o modelo com um problema de regressão 
    - Dois datasets: x e y
        - O dataset x tem ruído 

In [12]:
x = torch.arange(16,  dtype = torch.float32).reshape((8,2)) + torch.normal(0,0.5, (8,2))
y =  torch.arange(8,  dtype = torch.float32)
x, y

(tensor([[ 0.8909,  0.3575],
         [ 2.0997,  1.9977],
         [ 3.9524,  4.9909],
         [ 6.4150,  7.0071],
         [ 7.6181,  8.4024],
         [ 9.7568, 11.3322],
         [11.7904, 12.4074],
         [13.8729, 14.4491]]),
 tensor([0., 1., 2., 3., 4., 5., 6., 7.]))

In [13]:
y_hat = model.forward(x)
y_hat, y

(tensor([[ 0.3236],
         [ 2.5573],
         [ 6.7252],
         [ 9.2169],
         [11.0715],
         [15.0667],
         [16.2081],
         [18.8382]]),
 tensor([0., 1., 2., 3., 4., 5., 6., 7.]),
 8)

In [14]:
# quão bom ta esse modelo acima?
model.loss(y, y_hat)

tensor(28.7001)

O valor acima é a perda quadrática média pra este modelo, ou seja, quanto menor essa perda melhor será o modelo!

### Modelo com gradiente

- Para garantir que haja uma evolução, vamos usar o gradient descent (GD)

In [15]:
class Model2():
    # construtor inicializa os parametros
    def __init__(self, num_inputs):
        # w inicial: amostrando de uma distribuicao normal media 0 e desvio padrao 1
        self.w = torch.normal(0, 1, (num_inputs, 1), requires_grad=True)
        # b inicial: valor constante 1 ou 0, as vezes com 1/total de classes
        self.b = torch.zeros(1, requires_grad=True)

    # forward: de x até a saida
    def forward(self, X):
        # X w + b
        return X @ self.w + self.b # multipliação e soma matricial

    # funcao custo
    def loss(self, y, y_hat):
        yreshape = y.reshape(y_hat.shape)
        l = (y_hat - yreshape)**2/2
        return l.mean()

In [16]:
model2 = Model2(2)

y_hat = model2.forward(x)
y_hat, model2.loss(y, y_hat)

(tensor([[ 0.2342],
         [ 1.6947],
         [ 4.4072],
         [ 6.0716],
         [ 7.2906],
         [ 9.9021],
         [10.6932],
         [12.4338]], grad_fn=<AddBackward0>),
 tensor(6.3862, grad_fn=<MeanBackward0>))

* Por enquanto não vamos usar, mas com esse grad_fn ativado, já poderíamos implementar o gradient descent

*obs: esse modelo é quase um Perceptron, falta alguns ajustes para ser um propriamente dito (como por exemplo uma função de ativação)*

---